[build]
  command = "echo 'No build process needed'"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA routing fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

